// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-bible.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-bible.ts
var search_bible_default = defineTool({
  name: "search_bible",
  title: "Bibel durchsuchen",
  description: "Volltextsuche in den Bibel\xFCbersetzungen von BibleBot.Life. Gibt Buch, Kapitel, Vers, \xDCbersetzung und Verstext zur\xFCck.",
  inputSchema: {
    query: z.string().trim().min(2).describe("Suchbegriff oder Phrase, z.B. 'Hoffnung' oder 'Psalm 23'."),
    translation: z.string().trim().optional().describe("Optionaler \xDCbersetzungscode, z.B. 'LUT', 'SCH', 'ELB', 'EU', 'ZB'."),
    limit: z.number().int().optional().describe("Maximale Trefferzahl (Standard 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, translation, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 10, 1), 50);
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("bible_verses").select("book, chapter, verse, text, translation").textSearch("fts", query, { type: "websearch", config: "german" }).limit(max);
    if (translation) q = q.eq("translation", translation);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map((r) => `${r.book} ${r.chapter},${r.verse} (${r.translation}): ${r.text}`).join("\n") : "Keine Treffer.";
    return { content: [{ type: "text", text }], structuredContent: { verses: rows } };
  }
});

// src/lib/mcp/tools/list-prayer-wall.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_prayer_wall_default = defineTool2({
  name: "list_prayer_wall",
  title: "Gebetswand lesen",
  description: "Liest die freigegebenen, \xF6ffentlichen Gebetsanliegen der Gebetswand von BibleBot.Life.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximale Anzahl Anliegen (Standard 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("prayer_requests").select("id, content, author_name, is_anonymous, prayer_count, created_at").eq("is_approved", true).order("created_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (r) => `${r.is_anonymous ? "Anonym" : r.author_name ?? "Anonym"} (${r.prayer_count ?? 0} Gebete): ${r.content}`
    ).join("\n") : "Keine freigegebenen Anliegen.";
    return { content: [{ type: "text", text }], structuredContent: { requests: rows } };
  }
});

// src/lib/mcp/tools/list-my-journal-entries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_journal_entries_default = defineTool3({
  name: "list_my_journal_entries",
  title: "Meine Journal-Eintr\xE4ge",
  description: "Listet die eigenen Journal-Eintr\xE4ge (Impuls, Bibelstelle, Stimmung) der angemeldeten Person.",
  inputSchema: {
    limit: z3.number().int().optional().describe("Maximale Anzahl Eintr\xE4ge (Standard 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("journal_entries").select("id, content, prompt, verse_ref, mood, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map((r) => `${new Date(r.created_at).toISOString().slice(0, 10)} [${r.mood ?? "-"}] ${r.verse_ref ?? ""} ${r.content}`).join("\n") : "Noch keine Journal-Eintr\xE4ge.";
    return { content: [{ type: "text", text }], structuredContent: { entries: rows } };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_journal_entry_default = defineTool4({
  name: "create_journal_entry",
  title: "Journal-Eintrag erstellen",
  description: "Erstellt einen neuen Journal-Eintrag f\xFCr die angemeldete Person in BibleBot.Life.",
  inputSchema: {
    content: z4.string().trim().min(1).describe("Der Text des Eintrags."),
    verse_ref: z4.string().trim().optional().describe("Optionale Bibelstelle, z.B. 'Psalm 23,1'."),
    mood: z4.string().trim().optional().describe("Optionale Stimmung, z.B. 'dankbar', 'unruhig'."),
    prompt: z4.string().trim().optional().describe("Optionale Impulsfrage, auf die der Eintrag antwortet.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ content, verse_ref, mood, prompt }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("journal_entries").insert({ user_id: ctx.getUserId(), content, verse_ref: verse_ref ?? null, mood: mood ?? null, prompt: prompt ?? null }).select("id, content, verse_ref, mood, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Journal-Eintrag gespeichert." }],
      structuredContent: { entry: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/list-my-crosses.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_my_crosses_default = defineTool5({
  name: "list_my_crosses",
  title: "Meine Kreuze",
  description: "Listet die eigenen hochgeladenen Kreuz-Fotos aus den Kreuzwegen inklusive Status, Ort, Zitat und Freigabe-Link.",
  inputSchema: {
    status: z5.string().trim().optional().describe("Optionaler Statusfilter: 'pending', 'approved' oder 'rejected'."),
    limit: z5.number().int().optional().describe("Maximale Anzahl (Standard 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("cross_posts").select("id, slug, place_label, country, status, quote, quote_reference, amen_count, prayer_count, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      ...r,
      url: r.slug ? `https://biblebot.life/kreuzwege/${r.slug}` : null
    }));
    const text = rows.length ? rows.map((r) => `${r.place_label ?? "Ohne Ort"} \u2013 ${r.status} \u2013 ${r.url ?? "(kein Link)"}`).join("\n") : "Noch keine Kreuze hochgeladen.";
    return { content: [{ type: "text", text }], structuredContent: { crosses: rows } };
  }
});

// src/lib/mcp/tools/list-my-bible-moments.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_my_bible_moments_default = defineTool6({
  name: "list_my_bible_moments",
  title: "Meine Bibel-Momente",
  description: "Listet die konfigurierten Bibel-Momente (Trigger, Kanal, Sprache, Ruhezeiten) der angemeldeten Person.",
  inputSchema: {
    only_active: z6.boolean().optional().describe("Nur aktive Momente zur\xFCckgeben (Standard true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("bible_moments").select("id, trigger_type, label, delivery_channel, language, active, next_eligible_at, last_delivered_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (only_active !== false) q = q.eq("active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map((r) => `${r.label ?? r.trigger_type} \u2013 ${r.trigger_type} \u2013 ${r.delivery_channel} \u2013 ${r.active ? "aktiv" : "inaktiv"}`).join("\n") : "Keine Bibel-Momente konfiguriert.";
    return { content: [{ type: "text", text }], structuredContent: { moments: rows } };
  }
});

// src/lib/mcp/tools/bible-coaching.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var bible_coaching_default = defineTool7({
  name: "bible_coaching",
  title: "Bibel-Coaching",
  description: "Holt zu einem Lebensthema oder einer Stimmung passende Bibelstellen und gibt einen kurzen Coaching-Rahmen (PERMA, Logotherapie, Dankbarkeit, Vergebung) zur\xFCck. Keine Diagnose, sondern seelsorgerliche Orientierung.",
  inputSchema: {
    topic: z7.string().trim().min(2).describe("Lebensthema oder Frage, z.B. 'Angst vor der Zukunft' oder 'Dankbarkeit st\xE4rken'."),
    mood: z7.string().trim().optional().describe("Optionale Stimmung, z.B. '\xE4ngstlich', 'dankbar', 'einsam', 'motiviert'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic, mood }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nicht angemeldet." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const searchTerms = [topic, mood].filter(Boolean).join(" ");
    const { data, error } = await supabase.from("bible_verses").select("book, chapter, verse, text, translation").textSearch("fts", searchTerms, { type: "websearch", config: "german" }).limit(5);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const versesText = rows.length ? rows.map((r) => `${r.book} ${r.chapter},${r.verse} (${r.translation}): ${r.text}`).join("\n") : "Keine direkten Bibeltreffer.";
    const framework = [
      "Coaching-Rahmen:",
      "- Positive Emotion: Was l\xE4sst dich heute dankbar werden?",
      "- Engagement: Wo findest du Halt und Sinn? (Logotherapie)",
      "- Relationships: Wer steht an deiner Seite?",
      "- Meaning: Welchen kleinen Schritt kannst du heute gehen?",
      "- Accomplishment: Was ist schon gelungen?",
      "",
      "Passende Bibelstellen:",
      versesText,
      "",
      "Hinweis: BibleBot ersetzt keine professionelle Beratung. Bei akuten Krisen wende dich an die Telefonseelsorge (CH 143, DE/AT 0800 111 0 111)."
    ].join("\n");
    return { content: [{ type: "text", text: framework }], structuredContent: { verses: rows, topic, mood } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "swsthxftugjqznqjcfpk";
var mcp_default = defineMcp({
  name: "biblebotlife",
  title: "BibleBotLife",
  version: "0.1.1",
  instructions: "BibleBot.Life ist ein pers\xF6nlicher, christlicher Bibel-Begleiter. Wenn du Fragen stellst, nutze den Coaching-Ansatz: PERMA (Positive Psychologie), Logotherapie (Sinn), Dankbarkeit und Vergebung. Beginne mit Empathie, stelle eine kl\xE4rende Gegenfrage, suche dann mit `search_bible` nach passenden Stellen, pr\xFCfe Zitate sorgf\xE4ltig und gib den Vers-Text w\xF6rtlich wieder. Bei akuten Krisen (Selbstgef\xE4hrdung, Suizidgedanken, Gewalt) weise sofort auf professionelle Hilfe hin (Telefonseelsorge 143 in der Schweiz bzw. 0800 111 0 111 in Deutschland/\xD6sterreich) und wiederhole das Angebot. Keine medizinischen oder psychotherapeutischen Diagnosen. Keine Dogmen-Vermittlung. Keine Daten ausserhalb der freigegebenen Tools verwenden. Antworte auf Deutsch (Schweiz), ohne \xDF.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_bible_default,
    list_prayer_wall_default,
    list_my_journal_entries_default,
    create_journal_entry_default,
    list_my_crosses_default,
    list_my_bible_moments_default,
    bible_coaching_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
